### PR TITLE
New compile scheme

### PR DESCRIPTION
**Pull request by mihawk**
hi folks,

i develop, hack CB since a while, and few thing itch me, the compilation scheme is one of them
not be able to recompile deps and other CB apps, especially when hacking CB it self. 

this pull request allow compilation like n2o does 

https://github.com/synrc/active/

debian/ubuntu:
```bash
sudo apt-get install inotify-tools
```
for other system: mac or windows check this link
https://github.com/synrc/fs

i suggest you to have a look to their framework (clever people).

few thing to know is deps app are compiled with aleppo during the dev cycle
which is maybe bad.

benefit :
- shorter dev cycle, 
- shorter hacking CB cycle, 
- no difference about rendering time between dev & prod, 
  no more complain to being slow 
(in fact there is still a small difference)

cheers.

### CODE REVIEW

**Comment by dcy** [comment]
Good to hear that. But this pull request "The Travis CI build failed"

**Comment by danikp** [comment]
@dcy, actually, any PR will fail, as there is bunch of problems with dialyzer and even tests.

**Comment by mihawk** [comment]
i think i have fixed most of the problem for this pull request

**Comment by mihawk** [comment]
this time i hope it is my last commit on this PR,
 i didn't want to make a such big PR but it endup like this, 
issue fixed for 302, 227, 304, 322, 323: have to be confirmed, 
plz test it on windows and mac.

**Comment by mihawk** [comment]
beam going crazy :(

**Comment by danikp** [comment]
what do you mean?

**Comment by mihawk** [comment]
false alarm :),
i use entop to spot the pid consuming a lot of reduction,

(o2o_adm@xyz)7> process_info(erlang:list_to_pid("<0.542.0>"),[current_function]).
[{current_function,{paginate,page_before,4}}]

then 90% it is a bulshit code i made in one of my controller.

**Comment by danikp** [comment]
I personally have a problem with adding inotify-tools as dependency. We already have some issues with CB on windows because of merl. Adding another requirement for system library on linux, may cause problems for users who don't have privilages to install software on their system. 

I could propose to add configuration option, switching between old and new behavior. In such case, usage of inotify-tools will be optional.

**Comment by mihawk** [comment]
hi, it is possible to make it optional an keep the both compile scheme.
but need more work, i see what i can do.

**Comment by mihawk** [comment]
i had a quick look, it will be hard to maintain the both (personnaly i don't need it)
some extra work i can afford now (busy with my current project), 
maybe later (or someone can take over this branch to make it work with the old scheme)
i made this pull to make my dev life a bit better, and it is now
it fix many issue i had when i develop a CB App.
maybe you can propose this version to people want to try and 
get some feedback from the folk.

cheers
Chan.

**Comment by danikp** [comment]
@mihawk, problems? again?

**Comment by mihawk** [comment]
no problem so far,
but i don't want to maintain this code,
 i will be busy on other project.

**Pull request closed without merging**
